# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginRegister', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(default='2099-11-29'),
        ),
    ]
