# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginRegister', '0002_user_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default='9999-11-29'),
        ),
    ]
