# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 02:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='trainer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pkmn', to='logreg.User'),
            preserve_default=False,
        ),
    ]
