# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 02:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logreg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loser_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='losses', to='logreg.User')),
                ('winner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wins', to='logreg.User')),
            ],
        ),
    ]
