# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 05:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginRegister', '0003_auto_20170219_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('blog', models.TextField(max_length=1000)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('blog_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginRegister.User')),
            ],
        ),
    ]
